In [1]:
import numpy as np

### `array 는 리스트와 다르게 연산 가능`

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a[0]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3]))

In [7]:
# 행, 열
len(a), len(a[0])

(2, 3)

In [13]:
# AxB 행렬, 몇차원인지
a.shape, a.ndim

((2, 3), 2)

In [17]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b, b[0], b.shape, b.ndim

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 2, 3]),
 (3, 3),
 2)

In [18]:
np.argmax(b, axis = 1) # 열 기준으로 값이 제일 큰 원소의 인덱스(위치 반환)

array([2, 2, 2], dtype=int64)

In [20]:
c = np.array([[1234, 221, 11], [441, 51, 6], [71, 888, 91]])
np.argmax(c, axis = 0) # 행을 기준으로 값이 제일 큰 원소의 인덱스(위치 반환)

array([0, 0, 1], dtype=int64)

In [21]:
np.zeros(5) # 모든 값이 0 인 arr 생성

array([0., 0., 0., 0., 0.])

In [22]:
np.ones(5) # 모든 값이 1 인 arr 생성

array([1., 1., 1., 1., 1.])

In [35]:
f = np.zeros((2,4)) # 행렬로도 이용 가능.
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
g = np.ones((5,10))
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
np.arange(10) # 등차 수열

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1, 100, 3) # 초항이 1이고 공차가 3인 등차 수열

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [29]:
np.linspace(0, 100, 5) # 구간 시작점, 끝점, 구간 내 숫자 개수 (선형 구간)

array([  0.,  25.,  50.,  75., 100.])

In [30]:
np.logspace(0, 100, 5) # 구간 시작점, 끝점, 구간 내 숫자 개수 (로그 구간)

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [31]:
c

array([[1234,  221,   11],
       [ 441,   51,    6],
       [  71,  888,   91]])

In [32]:
c.T # 행렬 전치

array([[1234,  441,   71],
       [ 221,   51,  888],
       [  11,    6,   91]])

In [38]:
g.T.shape

(10, 5)

In [41]:
# 총 50개 의 값을 가지는 행렬을 규격에 맞게 reshape
g.T.reshape(25, 2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
g.T.reshape(13, 7) # 규격 안 맞으면 error

ValueError: cannot reshape array of size 50 into shape (13,7)

In [47]:
# 총 50 개
g.T.reshape(5, 10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [48]:
g.T.reshape(5, -1) # -1 이 행 or 열 에 있을 경우 
                   # 행 5 개를 기준으로 행렬이 완성되게 자동으로 채움

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
g.T.reshape(-1, 10) # -1 이 행 or 열 에 있을 경우 
                    # 열 10 개를 기준으로 행렬이 완성되게 자동으로 채움

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
g.T.reshape(-1) # 열 1 개로 다 채움

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
mt = g.T.reshape(1, 10, 5)
mt.shape, mt.ndim

((1, 10, 5), 3)

In [75]:
mt[0][2][1] # 3 차원

1.0

In [77]:
mt2 = g.T.reshape(10, 5)
mt2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
mt2[1][2][0] # 2 차원

IndexError: invalid index to scalar variable.

In [85]:
mt2, mt

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]))

In [86]:
mt2.shape, mt.shape # 겉보기로는 대괄호 하나 차이.

((10, 5), (1, 10, 5))

In [87]:
mt.shape # x, y, z 
         # x = frame, y = 행, z = 열

(1, 10, 5)